In [22]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print(df.columns.tolist())

Rows: 1000
Columns: 50
['crash_record_id', 'crash_date', 'posted_speed_limit', 'traffic_control_device', 'device_condition', 'weather_condition', 'lighting_condition', 'first_crash_type', 'trafficway_type', 'alignment', 'roadway_surface_cond', 'road_defect', 'report_type', 'crash_type', 'damage', 'date_police_notified', 'prim_contributory_cause', 'sec_contributory_cause', 'street_no', 'street_direction', 'street_name', 'beat_of_occurrence', 'num_units', 'crash_month', 'most_severe_injury', 'injuries_total', 'injuries_fatal', 'injuries_incapacitating', 'injuries_non_incapacitating', 'injuries_reported_not_evident', 'injuries_no_indication', 'injuries_unknown', 'crash_hour', 'crash_day_of_week', 'idot_control_no', 'intersection_related_i', 'hit_and_run_i', 'latitude', 'longitude', 'location', ':@computed_region_rpca_8um6', 'crash_date_est_i', 'private_property_i', 'photos_taken_i', 'lane_cnt', 'statements_taken_i', 'dooring_i', 'work_zone_i', 'work_zone_type', 'workers_present_i']

In [23]:
import requests

url = "https://api.nhtsa.gov/complaints/complaintsByVehicle"

params = {
    "make": "Honda",
    "model": "Accord",
    "modelYear": "2020"
}

response = requests.get(url, params=params)

print("Status Code:", response.status_code)
print(response.url)
print(response.text[:1000])

Status Code: 200
https://api.nhtsa.gov/complaints/complaintsByVehicle?make=Honda&model=Accord&modelYear=2020
{"count":364,"message":"Results returned successfully","results":[{"odiNumber":11770278,"manufacturer":"Honda (American Honda Motor Co.)","crash":false,"fire":false,"numberOfInjuries":0,"numberOfDeaths":0,"dateOfIncident":"09/01/2025","dateComplaintFiled":"10/10/2026","vin":"1hgcv2f34la","components":"ELECTRICAL SYSTEM,AIR BAGS","summary":"The Supplemental Restraint System Problem message along with the airbag light comes and goes on my dash randomly. Anytime I am able to take it to get scanned, it doesn\u2019t show up. Then when I\u2019m driving down the road it will randomly appear. It also appears sometimes when I first start the vehicle. My car has 66,200 miles on it and it first happened at 59,771 miles. The vehicle has never been roughly treated or heavy objects placed in the seats. I believe it is something electrical that is faulty because of failing Honda parts. My car shows there are no recalls for this, but other Accords do have a recall for this issue.","products":[{"type":

In [24]:
import requests
import pandas as pd

url = "https://data.cityofchicago.org/resource/85ca-t3if.json"

params = {
    "$limit": 1000
}

response = requests.get(url, params=params)

print("Status Code:", response.status_code)

data = response.json()

df = pd.DataFrame(data)

print(df.shape)
df.head()

Status Code: 200
(1000, 50)

,crash_record_id,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,...,:@computed_region_rpca_8um6,crash_date_est_i,private_property_i,photos_taken_i,lane_cnt,statements_taken_i,dooring_i,work_zone_i,work_zone_type,workers_present_i
0,006bc88aa00209dba00e7f4e77939f4cac6d1918b26e0f...,2020-07-28T21:37:00.000,25,NO CONTROLS,NO CONTROLS,CLEAR,DARKNESS,FIXED OBJECT,NOT DIVIDED,"CURVE, LEVEL",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8bd0613f9b39d21c255f4c0c6964a95418c448fe25015b...,2020-08-12T18:49:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DUSK,SIDESWIPE SAME DIRECTION,FOUR WAY,STRAIGHT AND LEVEL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54bb43f31434a799998791acfc9020eb0a09401332a08e...,2020-08-09T01:55:00.000,25,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",HEAD ON,NOT DIVIDED,STRAIGHT AND LEVEL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3d8f4ecfbdce63facb0497b9b00b4538e0f75fe7de3ad8...,2020-07-27T09:30:00.000,30,NO CONTROLS,NO CONTROLS,RAIN,DAYLIGHT,PARKED MOTOR VEHICLE,ONE-WAY,STRAIGHT AND LEVEL,...,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,b454dcc68b7f1cc9dbae0e8f8caa438d184ded31584554...,2020-08-10T16:30:00.000,30,NO CONTROLS,OTHER,RAIN,DAYLIGHT,OTHER NONCOLLISION,OTHER,STRAIGHT AND LEVEL,...,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
import boto3
import json

s3 = boto3.client("s3")

bucket = "chitown-crashes-api"
key = "raw/chicago_crashes/year=2024/part-0000.json"

response = s3.get_object(
    Bucket=bucket,
    Key=key,
    Range="bytes=0-100000"
)

text = response["Body"].read().decode("utf-8")

# Get the first complete JSON line
first_line = text.splitlines()[0]
record = json.loads(first_line)

print("Total columns:", len(record))

for column in record.keys():
    print(column)

JSONDecodeError: Unterminated string starting at: line 1 column 99985 (char 99984)

In [ ]:
import boto3
import json

s3 = boto3.client("s3")

bucket = "chitown-crashes-api"
key = "raw/chicago_crashes/year=2024/part-0000.json"

response = s3.get_object(
    Bucket=bucket,
    Key=key
)

data = json.load(response["Body"])

print(type(data))

<class 'list'>

In [ ]:
print("Total columns:", len(data[0]))

for column in data[0].keys():
    print(column)

Total columns: 38
crash_record_id
crash_date
posted_speed_limit
traffic_control_device
device_condition
weather_condition
lighting_condition
first_crash_type
trafficway_type
alignment
roadway_surface_cond
road_defect
report_type
crash_type
damage
date_police_notified
prim_contributory_cause
sec_contributory_cause
street_no
street_direction
street_name
beat_of_occurrence
num_units
crash_month
most_severe_injury
injuries_total
injuries_fatal
injuries_incapacitating
injuries_non_incapacitating
injuries_reported_not_evident
injuries_no_indication
injuries_unknown
crash_hour
crash_day_of_week
idot_control_no
latitude
longitude
location

In [ ]:
import boto3
import pyarrow.parquet as pq

s3 = boto3.client("s3")

bucket = "chitown-crashes-api"
key = "clean/crashes.parquet"

# Download the parquet file
s3.download_file(bucket, key, "crashes.parquet")

# Read only the schema/column names
parquet_file = pq.ParquetFile("crashes.parquet")

columns = parquet_file.schema.names

print("Total columns:", len(columns))

for column in columns:
    print(column)

ModuleNotFoundError: No module named 'pyarrow'

In [ ]:
import pandas as pd

df = pd.read_parquet(
    "s3://chitown-crashes-api/clean/crashes.parquet"
)

print(df.shape)
df.head()

(768803, 59)

,crash_record_id,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,...,crash_year,is_fatal,num_people,any_impaired,any_unbelted,any_pedestrian,any_bicycle,max_age,min_age,driver_age
0,0000c280b9c15e9ec96aa2eed34bf0f3ef1d604c6ea460...,2018-01-02 11:00:00,5,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,OTHER,STRAIGHT AND LEVEL,...,2018,0,1,False,False,False,False,65.0,65.0,65.0
1,000298245204df426f6f9aba90a495a0f85d89545b6a14...,2018-09-14 15:15:00,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,...,2018,0,3,False,False,False,False,63.0,25.0,63.0
2,00029e1d5deec1bd3241e585c4ec84fc5dd3570b9a3696...,2018-07-09 22:22:00,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,...,2018,0,2,False,False,False,False,26.0,25.0,26.0
3,0002fb938eb0feaea33820fa55b71e4ea0b332125e1510...,2018-03-06 15:00:00,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,...,2018,0,3,False,False,False,False,36.0,25.0,36.0
4,0005a7b841cef1f7f38b51a1bcc361c53873bcabc43401...,2018-02-06 14:05:00,30,TRAFFIC SIGNAL,UNKNOWN,SNOW,DAYLIGHT,REAR END,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,2018,0,2,False,False,False,False,44.0,44.0,44.0

In [ ]:
sample_df = df.sample(n=10000, random_state=42)

print(sample_df.shape)
sample_df.head()

(10000, 59)

,crash_record_id,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,...,crash_year,is_fatal,num_people,any_impaired,any_unbelted,any_pedestrian,any_bicycle,max_age,min_age,driver_age
56321,7877c53348b2b23685a77b1049c550ac049023a0093bad...,2018-03-06 08:45:00,30,NO CONTROLS,NO CONTROLS,CLOUDY/OVERCAST,DAYLIGHT,REAR END,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,...,2018,0,2,False,False,False,False,35.0,26.0,35.0
165305,6437f072d8edc910e282a0d5f194376ca123d9d76a09fd...,2019-09-10 08:30:00,20,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,ONE-WAY,STRAIGHT AND LEVEL,...,2019,0,1,False,False,False,False,NaN,NaN,NaN
79301,aa927a31c640c87050d0bd0bacb589abaa4ccf9f13d3e5...,2018-01-17 14:18:00,15,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,FIXED OBJECT,ALLEY,STRAIGHT AND LEVEL,...,2018,0,2,False,True,False,False,23.0,23.0,23.0
316109,dc944406d86d88ffab59bf292fa3b48876ded25ab1ec0c...,2020-12-12 14:30:00,20,OTHER,OTHER,CLOUDY/OVERCAST,DAYLIGHT,REAR TO SIDE,PARKING LOT,STRAIGHT AND LEVEL,...,2020,0,2,False,False,False,False,57.0,42.0,57.0
206246,bd163e7d669a4786fa9c263d002b06b4a624d00d422b4c...,2019-12-02 20:00:00,30,STOP SIGN/FLASHER,NO CONTROLS,CLEAR,DARKNESS,REAR END,PARKING LOT,STRAIGHT AND LEVEL,...,2019,0,2,False,False,False,False,25.0,25.0,25.0

In [ ]:
print(sample_df.columns.tolist())

['crash_record_id', 'crash_date', 'posted_speed_limit', 'traffic_control_device', 'device_condition', 'weather_condition', 'lighting_condition', 'first_crash_type', 'trafficway_type', 'alignment', 'roadway_surface_cond', 'road_defect', 'report_type', 'crash_type', 'private_property_i', 'damage', 'date_police_notified', 'prim_contributory_cause', 'sec_contributory_cause', 'street_no', 'street_direction', 'street_name', 'beat_of_occurrence', 'num_units', 'crash_month', 'most_severe_injury', 'injuries_total', 'injuries_fatal', 'injuries_incapacitating', 'injuries_non_incapacitating', 'injuries_reported_not_evident', 'injuries_no_indication', 'injuries_unknown', 'crash_hour', 'crash_day_of_week', 'idot_control_no', 'latitude', 'longitude', 'location', 'lane_cnt', 'hit_and_run_i', 'intersection_related_i', 'crash_date_est_i', 'work_zone_i', 'work_zone_type', 'statements_taken_i', 'dooring_i', 'photos_taken_i', 'workers_present_i', 'crash_year', 'is_fatal', 'num_people', 'any_impaired', 'any_unbelted', 'any_pedestrian', 'any_bicycle', 'max_age', 'min_age', 'driver_age']

In [ ]:
print(df["is_fatal"].value_counts())

print(df["is_fatal"].value_counts(normalize=True) * 100)

is_fatal
0    767908
1       895
Name: count, dtype: int64
is_fatal
0    99.883585
1     0.116415
Name: proportion, dtype: float64

In [ ]:
fatal = df[df["is_fatal"] == 1]

non_fatal = df[df["is_fatal"] == 0].sample(
    n=895 * 5,
    random_state=42
)

sample_df = pd.concat([fatal, non_fatal])

# Shuffle the rows
sample_df = sample_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

print(sample_df["is_fatal"].value_counts())
print(sample_df.shape)

is_fatal
0    4475
1     895
Name: count, dtype: int64
(5370, 59)

In [ ]:
features = [
    "posted_speed_limit",
    "weather_condition",
    "lighting_condition",
    "first_crash_type",
    "trafficway_type",
    "roadway_surface_cond",
    "prim_contributory_cause",
    "crash_hour",
    "crash_day_of_week",
    "num_units",
    "intersection_related_i",
    "hit_and_run_i",
    "any_impaired",
    "any_unbelted",
    "any_pedestrian",
    "any_bicycle",
    "driver_age"
]

X = sample_df[features]
y = sample_df["is_fatal"]

print(X.shape)
print(y.value_counts())

(5370, 17)
is_fatal
0    4475
1     895
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (4296, 17)
Testing: (1074, 17)

In [ ]:
print(X.shape)
print(y.shape)

(5370, 17)
(5370,)

In [ ]:
print(X_train.isnull().sum().sort_values(ascending=False))

intersection_related_i     3196
hit_and_run_i              3059
driver_age                  811
posted_speed_limit            0
weather_condition             0
roadway_surface_cond          0
lighting_condition            0
first_crash_type              0
trafficway_type               0
crash_day_of_week             0
crash_hour                    0
prim_contributory_cause       0
num_units                     0
any_impaired                  0
any_unbelted                  0
any_pedestrian                0
any_bicycle                   0
dtype: int64

In [ ]:
X_train = X_train.copy()
X_test = X_test.copy()

# Fill missing Yes/No values
X_train["intersection_related_i"] = X_train["intersection_related_i"].fillna("N")
X_test["intersection_related_i"] = X_test["intersection_related_i"].fillna("N")

X_train["hit_and_run_i"] = X_train["hit_and_run_i"].fillna("N")
X_test["hit_and_run_i"] = X_test["hit_and_run_i"].fillna("N")

# Fill missing driver ages with training median
median_age = X_train["driver_age"].median()

X_train["driver_age"] = X_train["driver_age"].fillna(median_age)
X_test["driver_age"] = X_test["driver_age"].fillna(median_age)

print(X_train.isnull().sum())

NameError: name 'X_train' is not defined

In [ ]:
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

# Make sure train and test have identical columns
X_train, X_test = X_train.align(
    X_test,
    join="left",
    axis=1,
    fill_value=0
)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (4296, 112)
Testing: (1074, 112)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model trained!")

Model trained!

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[847  36]
 [103  88]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.96      0.92       883
           1       0.71      0.46      0.56       191

    accuracy                           0.87      1074
   macro avg       0.80      0.71      0.74      1074
weighted avg       0.86      0.87      0.86      1074

In [ ]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance.head(15))

                                               Feature  Importance
1                                           crash_hour    0.090613
8                                           driver_age    0.082676
6                                       any_pedestrian    0.060520
3                                            num_units    0.059782
35                         first_crash_type_PEDESTRIAN    0.057952
2                                    crash_day_of_week    0.056572
5                                         any_unbelted    0.052875
28                       first_crash_type_FIXED OBJECT    0.032488
0                                   posted_speed_limit    0.031410
99   prim_contributory_cause_PHYSICAL CONDITION OF ...    0.030154
21           lighting_condition_DARKNESS, LIGHTED ROAD    0.026376
76   prim_contributory_cause_DISREGARDING TRAFFIC S...    0.017397
52                         trafficway_type_NOT DIVIDED    0.016409
23                         lighting_condition_DAYLIGHT    0.015843
104        prim_contributory_cause_UNABLE TO DETERMINE    0.015793

In [ ]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

log_model.fit(X_train, y_train)

print("Logistic Regression trained!")

Logistic Regression trained!

In [ ]:
log_pred = log_model.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print("Logistic Regression Confusion Matrix:")
print(confusion_matrix(y_test, log_pred))

print("\nLogistic Regression Classification Report:")
print(classification_report(y_test, log_pred))

Logistic Regression Confusion Matrix:
[[849  34]
 [ 83 108]]

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.96      0.94       883
           1       0.76      0.57      0.65       191

    accuracy                           0.89      1074
   macro avg       0.84      0.76      0.79      1074
weighted avg       0.88      0.89      0.88      1074

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

results = pd.DataFrame({
    "Model": ["Random Forest", "Logistic Regression"],
    
    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, log_pred)
    ],
    
    "Precision": [
        precision_score(y_test, y_pred),
        precision_score(y_test, log_pred)
    ],
    
    "Recall": [
        recall_score(y_test, y_pred),
        recall_score(y_test, log_pred)
    ],
    
    "F1 Score": [
        f1_score(y_test, y_pred),
        f1_score(y_test, log_pred)
    ]
})

results

                 Model  Accuracy  Precision    Recall  F1 Score
0        Random Forest  0.870577   0.709677  0.460733  0.558730
1  Logistic Regression  0.891061   0.760563  0.565445  0.648649

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train, y_train)

print("Gradient Boosting trained!")

Gradient Boosting trained!

In [ ]:
gb_pred = gb_model.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print("Gradient Boosting Confusion Matrix:")
print(confusion_matrix(y_test, gb_pred))

print("\nGradient Boosting Classification Report:")
print(classification_report(y_test, gb_pred))

Gradient Boosting Confusion Matrix:
[[850  33]
 [ 86 105]]

Gradient Boosting Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.96      0.93       883
           1       0.76      0.55      0.64       191

    accuracy                           0.89      1074
   macro avg       0.83      0.76      0.79      1074
weighted avg       0.88      0.89      0.88      1074

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

results = pd.DataFrame({
    "Model": [
        "Random Forest",
        "Logistic Regression",
        "Gradient Boosting"
    ],

    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, log_pred),
        accuracy_score(y_test, gb_pred)
    ],

    "Precision": [
        precision_score(y_test, y_pred),
        precision_score(y_test, log_pred),
        precision_score(y_test, gb_pred)
    ],

    "Recall": [
        recall_score(y_test, y_pred),
        recall_score(y_test, log_pred),
        recall_score(y_test, gb_pred)
    ],

    "F1 Score": [
        f1_score(y_test, y_pred),
        f1_score(y_test, log_pred),
        f1_score(y_test, gb_pred)
    ]
})

results

                 Model  Accuracy  Precision    Recall  F1 Score
0        Random Forest  0.870577   0.709677  0.460733  0.558730
1  Logistic Regression  0.891061   0.760563  0.565445  0.648649
2    Gradient Boosting  0.889199   0.760870  0.549738  0.638298

In [ ]:
import pandas as pd
import numpy as np

# Get importance from each model
rf_importance = model.feature_importances_
gb_importance = gb_model.feature_importances_

# Logistic regression uses coefficients
log_importance = np.abs(log_model.coef_[0])

importance_df = pd.DataFrame({
    "Feature": X_train.columns,
    "Random_Forest": rf_importance,
    "Logistic_Regression": log_importance,
    "Gradient_Boosting": gb_importance
})

# Normalize each model's importance to 0-1
for col in ["Random_Forest", "Logistic_Regression", "Gradient_Boosting"]:
    importance_df[col] = (
        importance_df[col] / importance_df[col].max()
    )

# Average all three models
importance_df["Average_Importance"] = importance_df[
    ["Random_Forest", "Logistic_Regression", "Gradient_Boosting"]
].mean(axis=1)

top_10 = importance_df.sort_values(
    "Average_Importance",
    ascending=False
).head(10)

top_10

,Feature,Random_Forest,Logistic_Regression,Gradient_Boosting,Average_Importance
6,any_pedestrian,0.667895,0.616961,1.000000,0.761619
99,prim_contributory_cause_PHYSICAL CONDITION OF ...,0.332773,1.000000,0.299109,0.543961
28,first_crash_type_FIXED OBJECT,0.358532,0.655081,0.383216,0.465610
5,any_unbelted,0.583531,0.369823,0.372552,0.441968
3,num_units,0.659754,0.287711,0.369055,0.438840
1,crash_hour,1.000000,0.007351,0.257649,0.421667
8,driver_age,0.912405,0.001480,0.119136,0.344341
76,prim_contributory_cause_DISREGARDING TRAFFIC S...,0.191998,0.623734,0.149351,0.321694
36,first_crash_type_REAR END,0.122887,0.657425,0.059482,0.279931
29,first_crash_type_HEAD ON,0.171580,0.470615,0.143119,0.261771

In [ ]:
def get_original_feature(feature):
    original_features = [
        "posted_speed_limit",
        "weather_condition",
        "lighting_condition",
        "first_crash_type",
        "trafficway_type",
        "roadway_surface_cond",
        "prim_contributory_cause",
        "crash_hour",
        "crash_day_of_week",
        "num_units",
        "intersection_related_i",
        "hit_and_run_i",
        "any_impaired",
        "any_unbelted",
        "any_pedestrian",
        "any_bicycle",
        "driver_age"
    ]

    for original in original_features:
        if feature == original or feature.startswith(original + "_"):
            return original

    return feature


importance_df["Original_Feature"] = (
    importance_df["Feature"].apply(get_original_feature)
)

grouped_importance = (
    importance_df
    .groupby("Original_Feature")[
        ["Random_Forest", "Logistic_Regression", "Gradient_Boosting"]
    ]
    .sum()
)

# Normalize again after grouping
for col in ["Random_Forest", "Logistic_Regression", "Gradient_Boosting"]:
    grouped_importance[col] = (
        grouped_importance[col] / grouped_importance[col].max()
    )

grouped_importance["Average_Importance"] = grouped_importance[
    ["Random_Forest", "Logistic_Regression", "Gradient_Boosting"]
].mean(axis=1)

top_10_factors = grouped_importance.sort_values(
    "Average_Importance",
    ascending=False
).head(10)

top_10_factors

NameError: name 'importance_df' is not defined

In [ ]:
factors = [
    "first_crash_type",
    "prim_contributory_cause",
    "weather_condition",
    "lighting_condition",
    "trafficway_type",
    "roadway_surface_cond",
    "any_impaired",
    "any_unbelted",
    "any_pedestrian",
    "any_bicycle",
    "hit_and_run_i",
    "intersection_related_i"
]

results = []

for factor in factors:
    stats = df.groupby(factor)["is_fatal"].agg(
        ["count", "sum", "mean"]
    ).reset_index()

    stats.columns = [
        "Condition",
        "Total_Crashes",
        "Fatal_Crashes",
        "Fatal_Rate"
    ]

    stats["Factor"] = factor
    stats["Fatal_Rate"] = stats["Fatal_Rate"] * 100

    results.append(stats)

fatal_factors = pd.concat(results, ignore_index=True)

fatal_factors.head()

,Condition,Total_Crashes,Fatal_Crashes,Fatal_Rate,Factor
0,ANGLE,84424,104,0.123188,first_crash_type
1,ANIMAL,574,6,1.045296,first_crash_type
2,FIXED OBJECT,37531,202,0.538222,first_crash_type
3,HEAD ON,6492,42,0.646950,first_crash_type
4,OTHER NONCOLLISION,2308,4,0.173310,first_crash_type

In [ ]:
reliable_factors = fatal_factors[
    fatal_factors["Total_Crashes"] >= 100
]

In [ ]:
overall_fatal_rate = df["is_fatal"].mean() * 100

print("Overall fatal crash rate:", overall_fatal_rate)

Overall fatal crash rate: 0.11641473823593301

In [ ]:
reliable_factors = reliable_factors.copy()

reliable_factors["Risk_Ratio"] = (
    reliable_factors["Fatal_Rate"] /
    overall_fatal_rate
)

In [ ]:
top_10_risk = reliable_factors.sort_values(
    "Risk_Ratio",
    ascending=False
).head(10)

top_10_risk[
    [
        "Factor",
        "Condition",
        "Total_Crashes",
        "Fatal_Crashes",
        "Fatal_Rate",
        "Risk_Ratio"
    ]
]

,Factor,Condition,Total_Crashes,Fatal_Crashes,Fatal_Rate,Risk_Ratio
48,prim_contributory_cause,PHYSICAL CONDITION OF DRIVER,4720,74,1.567797,13.467338
108,any_pedestrian,True,19998,270,1.350135,11.597630
9,first_crash_type,PEDESTRIAN,19123,237,1.239345,10.645948
33,prim_contributory_cause,EXCEEDING AUTHORIZED SPEED LIMIT,1035,11,1.062802,9.129445
1,first_crash_type,ANIMAL,574,6,1.045296,8.979071
66,weather_condition,SEVERE CROSS WIND GATE,118,1,0.847458,7.279642
6,first_crash_type,OVERTURNED,487,4,0.821355,7.055423
104,any_impaired,True,7745,51,0.658489,5.656409
3,first_crash_type,HEAD ON,6492,42,0.646950,5.557287
106,any_unbelted,True,61463,340,0.553178,4.751790

In [ ]:
reliable_factors = fatal_factors[
    (fatal_factors["Total_Crashes"] >= 500) &
    (fatal_factors["Fatal_Crashes"] >= 10)
].copy()

reliable_factors["Risk_Ratio"] = (
    reliable_factors["Fatal_Rate"] /
    overall_fatal_rate
)

top_10_risk = reliable_factors.sort_values(
    "Risk_Ratio",
    ascending=False
).head(10)

top_10_risk[
    [
        "Factor",
        "Condition",
        "Total_Crashes",
        "Fatal_Crashes",
        "Fatal_Rate",
        "Risk_Ratio"
    ]
]

,Factor,Condition,Total_Crashes,Fatal_Crashes,Fatal_Rate,Risk_Ratio
48,prim_contributory_cause,PHYSICAL CONDITION OF DRIVER,4720,74,1.567797,13.467338
108,any_pedestrian,True,19998,270,1.350135,11.597630
9,first_crash_type,PEDESTRIAN,19123,237,1.239345,10.645948
33,prim_contributory_cause,EXCEEDING AUTHORIZED SPEED LIMIT,1035,11,1.062802,9.129445
104,any_impaired,True,7745,51,0.658489,5.656409
3,first_crash_type,HEAD ON,6492,42,0.646950,5.557287
106,any_unbelted,True,61463,340,0.553178,4.751790
2,first_crash_type,FIXED OBJECT,37531,202,0.538222,4.623313
24,prim_contributory_cause,DISREGARDING TRAFFIC SIGNALS,15954,75,0.470102,4.038162
55,prim_contributory_cause,UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN...,3758,17,0.452368,3.885833

In [ ]:
 # Create a dummy crash with the exact same columns as training data
dummy_crash = pd.DataFrame(
    0,
    index=[0],
    columns=X_train.columns
)

# Numerical information
dummy_crash["posted_speed_limit"] = 55
dummy_crash["crash_hour"] = 2
dummy_crash["crash_day_of_week"] = 7
dummy_crash["num_units"] = 2
dummy_crash["driver_age"] = 25

# High-risk conditions found in our analysis
dummy_crash["any_impaired"] = 1
dummy_crash["any_unbelted"] = 1
dummy_crash["any_pedestrian"] = 1

# Categorical variables created by get_dummies
if "first_crash_type_PEDESTRIAN" in dummy_crash.columns:
    dummy_crash["first_crash_type_PEDESTRIAN"] = 1

if "prim_contributory_cause_PHYSICAL CONDITION OF DRIVER" in dummy_crash.columns:
    dummy_crash["prim_contributory_cause_PHYSICAL CONDITION OF DRIVER"] = 1

In [ ]:
rf_prediction = model.predict(dummy_crash)[0]
log_prediction = log_model.predict(dummy_crash)[0]
gb_prediction = gb_model.predict(dummy_crash)[0]

print("Random Forest:", rf_prediction)
print("Logistic Regression:", log_prediction)
print("Gradient Boosting:", gb_prediction)

Random Forest: 1
Logistic Regression: 1
Gradient Boosting: 1

In [ ]:
# Start with a blank crash
dummy_crash = pd.DataFrame(
    0,
    index=[0],
    columns=X_train.columns
)

# Numerical factors
dummy_crash["posted_speed_limit"] = 40
dummy_crash["crash_hour"] = 23       # 11 PM
dummy_crash["crash_day_of_week"] = 6
dummy_crash["num_units"] = 2
dummy_crash["driver_age"] = 32

# No obvious extreme risk factors
dummy_crash["any_impaired"] = 0
dummy_crash["any_unbelted"] = 0
dummy_crash["any_pedestrian"] = 0
dummy_crash["any_bicycle"] = 0

# Head-on collision
if "first_crash_type_HEAD ON" in dummy_crash.columns:
    dummy_crash["first_crash_type_HEAD ON"] = 1

# Darkness
if "lighting_condition_DARKNESS" in dummy_crash.columns:
    dummy_crash["lighting_condition_DARKNESS"] = 1

# Clear weather
if "weather_condition_CLEAR" in dummy_crash.columns:
    dummy_crash["weather_condition_CLEAR"] = 1

# Dry road
if "roadway_surface_cond_DRY" in dummy_crash.columns:
    dummy_crash["roadway_surface_cond_DRY"] = 1

In [26]:
rf_prediction = model.predict(dummy_crash)[0]
log_prediction = log_model.predict(dummy_crash)[0]
gb_prediction = gb_model.predict(dummy_crash)[0]

print("Random Forest:", "Fatal" if rf_prediction == 1 else "Non-Fatal")
print("Logistic Regression:", "Fatal" if log_prediction == 1 else "Non-Fatal")
print("Gradient Boosting:", "Fatal" if gb_prediction == 1 else "Non-Fatal")

NameError: name 'model' is not defined

In [27]:
rf_prob = model.predict_proba(dummy_crash)[0][1]
log_prob = log_model.predict_proba(dummy_crash)[0][1]
gb_prob = gb_model.predict_proba(dummy_crash)[0][1]

print(f"Random Forest score: {rf_prob:.2%}")
print(f"Logistic Regression score: {log_prob:.2%}")
print(f"Gradient Boosting score: {gb_prob:.2%}")

NameError: name 'model' is not defined